version: '3'
services:
  database:
    image: "postgres"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=testdb
    ports:
        - "5432:5432"